### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ryanhallock**
Suggestion to update with a more uniform format, with description on both branches.

### CODE REVIEW

**Comment by ryanhallock** [comment]
#28 #18 #25 #26 #4 #5 #10 #8 #12 #13 #27 #6

**Comment by ryanhallock** [comment]
We are missing a few people, aaron-berdecia, caysen-mayo, devon-leerssen and devin-wingfield. Please reply to this issue for what roles you want, and your GitHub username.

**Comment by Reynard-G** [comment]
ca908f4e3d7f6b20921686057c1fae15a5a16991

**Comment by ryanhallock** [comment]
This is not a merge request from development to main. This is a restructuring and unification between the two of the README.md. At the same time, we are still determining roles, which is why this draft has not been completed.

**Review by June3333 — APPROVED** [review]
It seems to meet all the requirements. + it looks good

**Pull request merged**
